version: "3.8"

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
    restart: always

  app:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - chromadb

volumes:
  chroma_data:
